# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5d75c7a8f63773e9f8718b35d444146"
name = "MapTheGap"
application_url = "https://connect.mapthegap.ai"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [ "https://connect.mapthegap.ai/auth/callback" ]
